name: Alerte Bourse

on:
  schedule:
    - cron: '0 * * * *'  #'*/10 * * * *' Toutes les 10 minutes
  workflow_dispatch:

jobs:
  check_stock:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer les dépendances
        run: |
          pip install -r requirements.txt

      - name: Exécuter le script
        env:
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python alerte_bourse.py       
